Small edge case fixes for whole genome analyses
This fixes two edge cases we ran into when running CNVkit in production:

- Empty antitarget files cause numpy merge errors:
```
File "/group/ngs/src/bcbio-nextgen/0.9.0/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 592, in do_fix
  cnarr.merge(anti_cnarr)
File "/group/ngs/src/bcbio-nextgen/0.9.0/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/cnarray.py", line 417
self.data = numpy.concatenate((self.data, other.data))
TypeError: invalid type promotion
```

- Add additional sanity checks in diagram plots to avoid segements over
  the start or end of chromosomes